services:
  postgres:
    image: postgres:14.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend-intern:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "8001:8001"
  frontend-intern:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-intern
    ports:
      - "5173:5173"
volumes:
  postgres_data:
