services:
  postgres:
    image: postgres:14.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    restart: unless-stopped
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_HOST=postgres
    depends_on:
      - postgres
    expose:
      - 8001
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VITE_API_BASE_URL=/api/v1
    command: npm run build
    volumes:
      - dist_data:/app/dist
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - dist_data:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
  dist_data:
