services:
  db_test:
    image: postgres:14.18
    container_name: e2e_postgres_test
    environment:
      POSTGRES_USER: postgrestest
      POSTGRES_PASSWORD: roottest
      POSTGRES_DB: postgrestest
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgrestest -d postgrestest"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_test_data:
